/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/plugins': RouteRecordInfo<'/plugins', '/plugins', Record<never, never>, Record<never, never>, '/plugins/autocomplate' | '/plugins/dialog' | '/plugins/locales' | '/plugins/moment' | '/plugins/storeGet' | '/plugins/storeSet'>,
    '/plugins/autocomplate': RouteRecordInfo<'/plugins/autocomplate', '/plugins/autocomplate', Record<never, never>, Record<never, never>>,
    '/plugins/dialog': RouteRecordInfo<'/plugins/dialog', '/plugins/dialog', Record<never, never>, Record<never, never>>,
    '/plugins/locales': RouteRecordInfo<'/plugins/locales', '/plugins/locales', Record<never, never>, Record<never, never>>,
    '/plugins/moment': RouteRecordInfo<'/plugins/moment', '/plugins/moment', Record<never, never>, Record<never, never>>,
    '/plugins/storeGet': RouteRecordInfo<'/plugins/storeGet', '/plugins/storeGet', Record<never, never>, Record<never, never>>,
    '/plugins/storeSet': RouteRecordInfo<'/plugins/storeSet', '/plugins/storeSet', Record<never, never>, Record<never, never>>,
    '/wireframes': RouteRecordInfo<'/wireframes', '/wireframes', Record<never, never>, Record<never, never>, '/wireframes/baseline' | '/wireframes/constrained' | '/wireframes/discord' | '/wireframes/extended-toolbar' | '/wireframes/inbox' | '/wireframes/side-navigation' | '/wireframes/steam' | '/wireframes/system-bar' | '/wireframes/three-column'>,
    '/wireframes/baseline': RouteRecordInfo<'/wireframes/baseline', '/wireframes/baseline', Record<never, never>, Record<never, never>>,
    '/wireframes/constrained': RouteRecordInfo<'/wireframes/constrained', '/wireframes/constrained', Record<never, never>, Record<never, never>>,
    '/wireframes/discord': RouteRecordInfo<'/wireframes/discord', '/wireframes/discord', Record<never, never>, Record<never, never>>,
    '/wireframes/extended-toolbar': RouteRecordInfo<'/wireframes/extended-toolbar', '/wireframes/extended-toolbar', Record<never, never>, Record<never, never>>,
    '/wireframes/inbox': RouteRecordInfo<'/wireframes/inbox', '/wireframes/inbox', Record<never, never>, Record<never, never>>,
    '/wireframes/side-navigation': RouteRecordInfo<'/wireframes/side-navigation', '/wireframes/side-navigation', Record<never, never>, Record<never, never>>,
    '/wireframes/steam': RouteRecordInfo<'/wireframes/steam', '/wireframes/steam', Record<never, never>, Record<never, never>>,
    '/wireframes/system-bar': RouteRecordInfo<'/wireframes/system-bar', '/wireframes/system-bar', Record<never, never>, Record<never, never>>,
    '/wireframes/three-column': RouteRecordInfo<'/wireframes/three-column', '/wireframes/three-column', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/00_samples/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/00_samples/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/00_samples/plugins.vue': {
      routes: '/plugins' | '/plugins/autocomplate' | '/plugins/dialog' | '/plugins/locales' | '/plugins/moment' | '/plugins/storeGet' | '/plugins/storeSet'
      views: 'default'
    }
    'src/pages/00_samples/plugins/autocomplate.vue': {
      routes: '/plugins/autocomplate'
      views: never
    }
    'src/pages/00_samples/plugins/dialog.vue': {
      routes: '/plugins/dialog'
      views: never
    }
    'src/pages/00_samples/plugins/locales.vue': {
      routes: '/plugins/locales'
      views: never
    }
    'src/pages/00_samples/plugins/moment.vue': {
      routes: '/plugins/moment'
      views: never
    }
    'src/pages/00_samples/plugins/storeGet.vue': {
      routes: '/plugins/storeGet'
      views: never
    }
    'src/pages/00_samples/plugins/storeSet.vue': {
      routes: '/plugins/storeSet'
      views: never
    }
    'src/pages/00_samples/wireframes.vue': {
      routes: '/wireframes' | '/wireframes/baseline' | '/wireframes/constrained' | '/wireframes/discord' | '/wireframes/extended-toolbar' | '/wireframes/inbox' | '/wireframes/side-navigation' | '/wireframes/steam' | '/wireframes/system-bar' | '/wireframes/three-column'
      views: 'default'
    }
    'src/pages/00_samples/wireframes/baseline.vue': {
      routes: '/wireframes/baseline'
      views: never
    }
    'src/pages/00_samples/wireframes/constrained.vue': {
      routes: '/wireframes/constrained'
      views: never
    }
    'src/pages/00_samples/wireframes/discord.vue': {
      routes: '/wireframes/discord'
      views: never
    }
    'src/pages/00_samples/wireframes/extended-toolbar.vue': {
      routes: '/wireframes/extended-toolbar'
      views: never
    }
    'src/pages/00_samples/wireframes/inbox.vue': {
      routes: '/wireframes/inbox'
      views: never
    }
    'src/pages/00_samples/wireframes/side-navigation.vue': {
      routes: '/wireframes/side-navigation'
      views: never
    }
    'src/pages/00_samples/wireframes/steam.vue': {
      routes: '/wireframes/steam'
      views: never
    }
    'src/pages/00_samples/wireframes/system-bar.vue': {
      routes: '/wireframes/system-bar'
      views: never
    }
    'src/pages/00_samples/wireframes/three-column.vue': {
      routes: '/wireframes/three-column'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
