/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/accounts': RouteRecordInfo<'/accounts', '/accounts', Record<never, never>, Record<never, never>, '/accounts/' | '/accounts/login' | '/accounts/logoff' | '/accounts/logon' | '/accounts/logout'>,
    '/accounts/': RouteRecordInfo<'/accounts/', '/accounts', Record<never, never>, Record<never, never>>,
    '/accounts/login': RouteRecordInfo<'/accounts/login', '/accounts/login', Record<never, never>, Record<never, never>>,
    '/accounts/logoff': RouteRecordInfo<'/accounts/logoff', '/accounts/logoff', Record<never, never>, Record<never, never>>,
    '/accounts/logon': RouteRecordInfo<'/accounts/logon', '/accounts/logon', Record<never, never>, Record<never, never>>,
    '/accounts/logout': RouteRecordInfo<'/accounts/logout', '/accounts/logout', Record<never, never>, Record<never, never>>,
    '/contents': RouteRecordInfo<'/contents', '/contents', Record<never, never>, Record<never, never>, '/contents/' | '/contents/accounts' | '/contents/bars' | '/contents/foos' | '/contents/items' | '/contents/sessions'>,
    '/contents/': RouteRecordInfo<'/contents/', '/contents', Record<never, never>, Record<never, never>>,
    '/contents/accounts': RouteRecordInfo<'/contents/accounts', '/contents/accounts', Record<never, never>, Record<never, never>>,
    '/contents/bars': RouteRecordInfo<'/contents/bars', '/contents/bars', Record<never, never>, Record<never, never>>,
    '/contents/foos': RouteRecordInfo<'/contents/foos', '/contents/foos', Record<never, never>, Record<never, never>>,
    '/contents/items': RouteRecordInfo<'/contents/items', '/contents/items', Record<never, never>, Record<never, never>>,
    '/contents/sessions': RouteRecordInfo<'/contents/sessions', '/contents/sessions', Record<never, never>, Record<never, never>>,
    '/examples': RouteRecordInfo<'/examples', '/examples', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/01_frontend/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/01_frontend/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/01_frontend/accounts.vue': {
      routes: '/accounts' | '/accounts/' | '/accounts/login' | '/accounts/logoff' | '/accounts/logon' | '/accounts/logout'
      views: 'default'
    }
    'src/pages/01_frontend/accounts/index.vue': {
      routes: '/accounts/'
      views: never
    }
    'src/pages/01_frontend/accounts/login.vue': {
      routes: '/accounts/login'
      views: never
    }
    'src/pages/01_frontend/accounts/logoff.vue': {
      routes: '/accounts/logoff'
      views: never
    }
    'src/pages/01_frontend/accounts/logon.vue': {
      routes: '/accounts/logon'
      views: never
    }
    'src/pages/01_frontend/accounts/logout.vue': {
      routes: '/accounts/logout'
      views: never
    }
    'src/pages/01_frontend/contents.vue': {
      routes: '/contents' | '/contents/' | '/contents/accounts' | '/contents/bars' | '/contents/foos' | '/contents/items' | '/contents/sessions'
      views: 'default'
    }
    'src/pages/01_frontend/contents/index.vue': {
      routes: '/contents/'
      views: never
    }
    'src/pages/01_frontend/contents/accounts.vue': {
      routes: '/contents/accounts'
      views: never
    }
    'src/pages/01_frontend/contents/bars.vue': {
      routes: '/contents/bars'
      views: never
    }
    'src/pages/01_frontend/contents/foos.vue': {
      routes: '/contents/foos'
      views: never
    }
    'src/pages/01_frontend/contents/items.vue': {
      routes: '/contents/items'
      views: never
    }
    'src/pages/01_frontend/contents/sessions.vue': {
      routes: '/contents/sessions'
      views: never
    }
    'src/pages/01_frontend/examples.vue': {
      routes: '/examples'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
